### ISSUE TITLE
Avoid the use of important in your css

### ISSUE THREAD

**Issue by eobaah** [elraphty/ResoltzTest#4]
Where possible, I like to use source order, specificity, and inheritance to override styles. Let's avoid using important unless it's the absolute last resort.

https://uxengineer.com/css-specificity-avoid-important-css/

https://github.com/elraphty/ResoltzTest/blob/aa226d5ec3a27801cb280639e11bff03b1fac156/style/style.css#L17

**Comment by elraphty** [comment]
Done i have removed all !important tags from my css file using the source order rule i.e i placed my style  link under my bootstrap link

**Comment by eobaah** [comment]
👍🏿Nice work! Ordering your CSS links is another great way to manage
priority of styles.
